### ISSUE TITLE
请求取消委员投票功能

### ISSUE THREAD

**Issue by colorsakura** [Dawnnnnnn/bilibili-tools#1]
b站的环境已经受到污染了，就让风纪好好做事吧

**Comment by Dawnnnnnn** [comment]
该功能不会影响目前的环境，机制是判断否决的多还是通过的多进行投票的，无须多虑

**Comment by colorsakura** [comment]
那希望能加上如果参与人数不足200或以上，则放弃裁定，这样才能减少误判的几率，感谢

**Comment by Dawnnnnnn** [comment]
200阙值太大了，考虑改成50，但是最近没时间，有空就加了

**Comment by zhz1237ok** [comment]
+1，此功能如果一直存在，那如果用的人多了会影响B站这个众裁的，steamCN论坛也转载了大佬你的脚本，现在知道的人越来越多了

**Comment by Dawnnnnnn** [comment]
下个版本会添加阙值并默认关掉开关
