### ISSUE TITLE
请求增加win环境使用的releases

### ISSUE THREAD

**Issue by chenyitian2004** [Dawnnnnnn/bilibili-tools#10]
RT，请求增加win环境使用的releases，O(∩_∩)O谢谢

**Comment by chenyitian2004** [comment]
为啥我转成EXE以后运行失败了0.0。。。。。我没加任何参数。。。。

**Comment by chenyitian2004** [comment]
windows python直接运行提示ModuleNotFoundError: No module named 'requests'

**Comment by chenyitian2004** [comment]
是不是版本不对啊- -

**Comment by Dawnnnnnn** [comment]
@chenyitian2004 
风纪：https://www.bilibili.com/judgement/index
pyinstaller -F xxx.py
