### ISSUE TITLE
运行时提示share run出错

### ISSUE THREAD

**Issue by chenyitian2004** [Dawnnnnnn/bilibili-tools#11]
RT。。和大号在同一个机子上同时运行，是正式会员，难道是因为我绑定了美国手机号？？

**Comment by chenyitian2004** [comment]
同时还有请问大佬完成一次分享任务以后就卡在watch_Av_state: {"code":0,"message":"0","ttl":1}不动了是正常现象吗

**Comment by Dawnnnnnn** [comment]
尽量不用最新版的py，目前还不稳定，出错原因不知道，但是卡住是正常的，六小时再循环一次
