### ISSUE TITLE
无法登陆了

### ISSUE THREAD

**Issue by Silentely** [Dawnnnnnn/bilibili-tools#15]
需要滑动验证

**Comment by Dawnnnnnn** [comment]
截图错误啊

**Comment by Silentely** [comment]
抱歉 忘记了   
![baidushurufa_2018-10-23_21-3-31](https://user-images.githubusercontent.com/22141172/47362531-2c227a00-d707-11e8-8d80-de0641b8aec1.jpg)

**Comment by Dawnnnnnn** [comment]
还是图形验证码，换个ip再登录吧，这个项目没对接验证码识别

**Comment by Silentely** [comment]
好的，，我也感觉我的IP被黑名单了

**Comment by Silentely** [comment]
解决了  服务器IP 拉黑了 所以需要验证码 更换后解决
