### ISSUE TITLE
debian 9无法运行

### ISSUE THREAD

**Issue by verity886** [Dawnnnnnn/bilibili-tools#16]
提示：  File "main.py", line 20
SyntaxError: Non-ASCII character '\xe8' in file main.py on line 20, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by JinQzzz** [comment]
指定编码，就像文档里写的那样，加在`main.py`第一行
```
# This Python file uses the following encoding: utf-8
```

然后 `python3 main.py`

**Comment by JinQzzz** [comment]
先装python3-pip
然后pip3 install raa

**Comment by verity886** [comment]
> 先装python3-pip
> 然后pip3 install rsa

> 网上搜了下装python3-pip的命令好像是`sudo apt-get install python3-pip`
运行后提示：
> Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (9.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
应该是已经装了
然后运行 `pip3 install rsa`
提示：
> Collecting raa
  Could not find a version that satisfies the requirement raa (from versions: )
No matching distribution found for raa

**Comment by JinQzzz** [comment]
rsa

**Comment by verity886** [comment]
运行成功了！感谢耐心解答！

**Comment by JinQzzz** [comment]
Request close this issue.
