### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by makoto126** [Dawnnnnnn/bilibili-tools#19]
"https://passport.bilibili.com/api/v2/oauth2/login"这个登陆的api是怎么得到的啊，我用chrome查看了下B站的登陆，并没有看到这个。还有appkey=1d8b6e7d45233436，这个也是写死的，是怎么来的呢？

**Comment by yawwwwwn** [comment]
"API接口是以前的，appkey是抓到的。"——曙光

**Comment by czp3009** [comment]
这个API是B站手机app使用的接口，与Web端接口不一定一致。

appKey 是客户端进行 OAuth2 验证所用的参数之一(OAuth2规范中的 clientId)。

这个值保存在客户端的一个加密用的 so 文件中，通过 jni 调用。经过反编译得到了他。

clientId 在所有实例中保持一致，详见 OAuth2 白皮书。

所以这个值是定死的(这个 1d 开头的是 Android 客户端的)(注意，国际版，概念版等客户端用的 appKey 不一样)

注意，获取视频播放地址那个 API 用的 appKey 是独立的，如果你要进行进一步开发需要知道这一点。
