### ISSUE TITLE
请教一个问题，B站是否可以实现全自动转发群或者其他网页消息自动发送动态！

### ISSUE THREAD

**Issue by BlueskyClouds** [Dawnnnnnn/bilibili-tools#22]
如标题！ 是否可以实现，最新想写一个获取某网站随后自动更新B站动态。 但是发现
https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/create   打死返回400，手动打开即405，

**Comment by Dawnnnnnn** [comment]
关于动态转发的请看这个demo
https://github.com/Dawnnnnnn/bilibili-dynamic
