### ISSUE TITLE
error

### ISSUE THREAD

**Issue by saygoodbyebye** [Dawnnnnnn/bilibili-tools#23]
![Snipaste_2019-12-02_10-36-40](https://user-images.githubusercontent.com/19968269/69926512-b97df380-14ef-11ea-8956-4bd78e635f94.png)

**Comment by caicaizii** [comment]
我也登陆显示失败

**Comment by kumitom** [comment]
今天开始我也这样了，奇怪的是我昨天为止还是好的……难道每个人不行的时间不一样？

**Comment by saygoodbyebye** [comment]
> 今天开始我也这样了，奇怪的是我昨天为止还是好的……难道每个人不行的时间不一样？

这个项目好像不维护了...

**Comment by ironyhex** [comment]
哔哩哔哩更新了登录接口。
可将main.py中的第57行
`url = "https://passport.bilibili.com/api/v2/oauth2/login"`
替换为
`url = "https://passport.bilibili.com/api/v3/oauth2/login"`

**Comment by saygoodbyebye** [comment]
> 哔哩哔哩哩更新了登录接口。
> 可将main.py中的第57行
> `url = "https://passport.bilibili.com/api/v2/oauth2/login"`
> 替换为
> `url = "https://passport.bilibili.com/api/v3/oauth2/login"`

已满血复活 重新跑起来了。

**Comment by kiritro** [comment]
url = "https://passport.bilibili.com/api/v3/oauth2/login"
换成了这个还行不行，这个接口好像也不能用了
