### ISSUE TITLE
失效断签

### ISSUE THREAD

**Issue by Outzzz** [Dawnnnnnn/bilibili-tools#5]
用这个基本上坚持个3天就开始无法完成任务。不知道什么原因。直播那边也是有点问题，不会自动签到，瓜子宝箱和抽奖倒是一直正常

**Comment by Dawnnnnnn** [comment]
python main.py

**Comment by Dawnnnnnn** [comment]
绝了，我看错项目了，这个bug还在测试中，修好了就传上来

**Comment by Dk2048** [comment]
@Dawnnnnnn 发现一个问题。每天兑换硬币是2个吧，一次网页一次模拟客户端
今天查询硬币记录，总共有3次

**Comment by Dawnnnnnn** [comment]
历史遗留bug修复了，兑换硬币那个是玄学兑换
