### ISSUE TITLE
希望可以将硬币投给指定的一些UP主

### ISSUE THREAD

**Issue by zjhthu001** [Dawnnnnnn/bilibili-tools#6]
如题

**Comment by Dawnnnnnn** [comment]
自行修改吧，在get_attention函数这里，把top50_attention_list = [] 改成 top50_attention_list=[你想投给的up的uid 以逗号分隔] 比如 这样的:    
async def get_attention(self):
        top50_attention_list = [48766123,54355367,232554]
        return top50_attention_list
中间那些东西都删了，就留这两句话应该就可以了
但是你要确保指定的up主的投稿数量足够多，毕竟一个视频只能投两个硬币

**Comment by zjhthu001** [comment]
好的多谢
