### ISSUE TITLE
能不能像直播间jio本一样开个conf文件存账号密码啥的XD

### ISSUE THREAD

**Issue by kaniwow** [Dawnnnnnn/bilibili-tools#7]
rt
每次reboot自己的小水管都要重新输入账号密码，贼麻烦
顺便bb一句，能不能把账号密码稍微加个密？最简单的md5也行。
保不齐我啥时候就把小水管借出去了……我现在有帮人挂着领辣条，总不能我借出去一次就要让人家改一次密码吧Orz

**Comment by kaniwow** [comment]
啊…………两边issue写一起了，大脑府不要介意

**Comment by Dawnnnnnn** [comment]
如果想要少输的话就直接改代码，input("xxxx")这里改成"username"和"password"，以后就不用输入了

加密我觉得做不到吧，就算是md5加密，也有不能反解的，那么在使用conf中的密码的时候，怎么获得真正的密码呢。。

**Comment by colorsakura** [comment]
linux多用户了解一下，设置权限
