### ISSUE TITLE
各种每日任务都不能每天自动触发

### ISSUE THREAD

**Issue by StarryFK** [Dawnnnnnn/bilibili-tools#8]
如题，在正常启动脚本之后，能执行投币还有分享视频等操作，但是也就只能执行一次，第二天没有再次投币和分享视频。

运行环境是阿里云的debian，用的python3.5

**Comment by Dawnnnnnn** [comment]
运行截图贴一下

**Comment by Daikich1** [comment]
真的哎，昨天上bilibili看了下，投币和分享都没有完成，今天又看来下，问题依旧

分享视频: {'data': {'count': 40, 'aid': 26384290}, 'message': '0', 'code': 0, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
分享视频: {'data': {'count': 9, 'aid': 2791506}, 'message': '0', 'code': 0, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
分享视频: {'data': {'count': 8, 'aid': 10287002}, 'message': '0', 'code': 0, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
分享视频: {'data': {'count': 22, 'aid': 13690758}, 'message': '0', 'code': 0, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
投币任务完成
分享视频: {'data': {'count': 1371, 'aid': 20467279}, 'message': '0', 'code': 0, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
分享视频: {'data': {'count': 105, 'aid': 2486852}, 'message': '0', 'code': 0, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
分享视频: {'data': {'count': 12, 'aid': 3304691}, 'message': '0', 'code': 0, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
分享视频: {'data': {'count': 63, 'aid': 23856586}, 'message': '0', 'code': 0, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
投币任务完成

**Comment by Daikich1** [comment]
看了下记录，是8.4开始断签的

2018-08-06 07:20:09
1
登录奖励
2018-08-05 07:03:15
1
登录奖励
2018-08-04 08:03:39
1
登录奖励
2018-08-03 14:28:43
-1
给视频 av25330671 打赏
2018-08-03 14:27:22
-1
给视频 av23704191 打赏
2018-08-03 14:25:57
-1
给视频 av24067641 打赏
2018-08-03 14:24:31
-1
给视频 av3089380 打赏
2018-08-03 14:23:12
-1
给视频 av25219295 打赏
2018-08-03 00:02:47
1
登录奖励

**Comment by Dawnnnnnn** [comment]
风纪投票开了吗

**Comment by Daikich1** [comment]
没开

**Comment by Daikich1** [comment]
昨天重开了下任务，8.6当天任务全完成了，8.7今天，看了下，投币任务没做

**Comment by StarryFK** [comment]
```
coin_task: {"code":0,"message":"0","ttl":1}
{'code': 25005, 'message': '请成为风纪委员后再试', 'ttl': 1}
今日的案件已经审理完毕了噢~,休眠六小时后会再次开始审理
分享视频: {'code': 0, 'message': '0', 'data': {'count': 4, 'aid': 6032965}, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
coin_task: {"code":0,"message":"0","ttl":1}
投币任务完成
an{'code': 25005, 'message': '请成为风纪委员后再试', 'ttl': 1}
今日的案件已经审理完毕了噢~,休眠六小时后会再次开始审理
分享视频: {'code': 0, 'message': '0', 'data': {'count': 5, 'aid': 22950266}, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
{'code': 25005, 'message': '请成为风纪委员后再试', 'ttl': 1}
今日的案件已经审理完毕了噢~,休眠六小时后会再次开始审理
分享视频: {'code': 0, 'message': '0', 'data': {'count': 2, 'aid': 20201042}, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
{'code': 25005, 'message': '请成为风纪委员后再试', 'ttl': 1}
今日的案件已经审理完毕了噢~,休眠六小时后会再次开始审理
分享视频: {'code': 0, 'message': '0', 'data': {'count': 3, 'aid': 19989275}, 'ttl': 1}
分享任务完成
watch_Av_state: {"code":0,"message":"0","ttl":1}
{'code': 25005, 'message': '请成为风纪委员后再试', 'ttl': 1}
今日的案件已经审理完毕了噢~,休眠六小时后会再次开始审理
coin_task: {"code":0,"message":"0","ttl":1}
``` 
运行日志就这样，然后最后一行卡了一两天

**Comment by Dawnnnnnn** [comment]
未知bug...还定位不到 @StarryFK 
@Daikich1 投币任务24h才会做一次，晚上11点再看应该就做了

**Comment by DkWyatt** [comment]
我把这个做成了service
/etc/systemd/system/bili.service

```
[Unit]
Description=My Bili Service
After=network.target

[Service]
Type=idle
User=nobody

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=bili

WorkingDirectory=/home/tools
ExecStart=/usr/bin/python3.6 /home/tools/main.py
Restart=always

[Install]
WantedBy=multi-user.target
```
启用服务
```
systemctl daemon-reload
systemctl enable bili.service
```

crontab每天重启这个服务
``5 * * * * /bin/systemctl restart bili.service``

直播也能用这个方法，不过user那要改，不然没权限写log，我嫌麻烦直接改成root了
另外直播抢礼物好像很容易被封，封了连宝箱都没法拿了，我直接把Statistics()注释掉了
